import { createFileRoute } from "@tanstack/react-router";
import { BellRing, Download, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip as ReTooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";

import { PageHero, Section, StatCard } from "@/components/portal/page-shell";
import { RiskGauge } from "@/components/portal/risk-gauge";
import { SpeakButton } from "@/components/portal/speak-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { usePortal } from "@/lib/portal-store";
import { BAND_META, ESTABLISHMENTS, bandOf } from "@/lib/shram-data";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/scorecard")({
  head: () => ({
    meta: [
      { title: "Risk-Based Compliance Scorecard — SHRAM SATHI" },
      {
        name: "description",
        content:
          "Look up any establishment by Shram Pehchan Sankhya (LIN) for a composite 0-100 compliance score, clause-by-clause statutory findings, penalty exposure and plain-language remedies.",
      },
      { property: "og:title", content: "Risk-Based Compliance Scorecard — SHRAM SATHI" },
      {
        property: "og:description",
        content: "Composite risk scoring by LIN with statutory citations, penalty exposure and resolution guidance.",
      },
    ],
  }),
  component: ScorecardPage,
});

const SEV_ICON: Record<string, string> = { critical: "⛔", major: "⚠️", minor: "🟡", compliant: "✅" };

function ScorecardPage() {
  const { lang, iconMode, toggleIconMode } = usePortal();
  const [query, setQuery] = useState("");
  const [lin, setLin] = useState(ESTABLISHMENTS[0]!.lin);
  const est = ESTABLISHMENTS.find((e) => e.lin === lin) ?? ESTABLISHMENTS[0]!;

  const matches = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return ESTABLISHMENTS;
    return ESTABLISHMENTS.filter(
      (e) => e.lin.toLowerCase().includes(q) || e.name.toLowerCase().includes(q) || e.district.toLowerCase().includes(q),
    );
  }, [query]);

  const open = est.findings.filter((f) => f.severity !== "compliant");
  const meta = BAND_META[bandOf(est.score)];

  const narration =
    lang === "hi"
      ? `${est.name} का अनुपालन स्कोर ${est.score} में से 100 है। जोखिम स्तर ${meta.labelHi}। ${open.length} वैधानिक समस्याएँ लंबित हैं।`
      : `${est.name} has a compliance score of ${est.score} out of 100. Risk level ${meta.label}. ${open.length} statutory issues are open.`;

  const exportCard = () => {
    const lines = [
      "SHRAM SATHI — RISK-BASED COMPLIANCE SCORECARD",
      "Ministry of Labour & Employment, Government of India",
      "",
      `Establishment      : ${est.name}`,
      `Shram Pehchan (LIN): ${est.lin}`,
      `Sector / District  : ${est.sector} / ${est.district}`,
      `Workers on roll    : ${est.workers}`,
      `Composite score    : ${est.score}/100 (${meta.label})`,
      `Last inspection    : ${est.lastInspection}`,
      "",
      "FINDINGS",
      ...est.findings.flatMap((f) => [
        `- [${f.severity.toUpperCase()}] ${f.title}`,
        `  ${f.section}`,
        `  Observation: ${f.observation}`,
        `  Penalty    : ${f.penalty}`,
        `  Resolve    : ${f.resolve}`,
        "",
      ]),
      "Generated by the SHRAM SATHI deterministic statutory rule engine (v4.2).",
    ].join("\n");
    const url = URL.createObjectURL(new Blob([lines], { type: "text/plain" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = `shram-sathi-scorecard-${est.lin}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Scorecard exported", { description: `${est.lin} summary downloaded.` });
  };

  return (
    <>
      <PageHero
        eyebrow="PS-05 · Module 3"
        title="Dynamic Risk-Based Compliance Scorecard"
        titleHi="गतिशील जोखिम आधारित अनुपालन स्कोरकार्ड"
        description="A composite, explainable score per establishment — built from clause-level statutory findings, weighted by severity, worker exposure and recurrence."
        actions={
          <>
            <SpeakButton text={narration} size="default" />
            <Button variant="outline" className="gap-1.5" onClick={exportCard}>
              <Download className="size-4" aria-hidden /> Export summary
            </Button>
            <Button
              className="gap-1.5"
              onClick={() =>
                toast.success("Notification dispatched", {
                  description: `SMS + email advisory sent to ${est.name} and the ${est.district} facilitator office.`,
                })
              }
            >
              <BellRing className="size-4" aria-hidden /> Notify establishment
            </Button>
          </>
        }
      />

      <Section>
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Establishment lookup</CardTitle>
            <CardDescription>Search by Shram Pehchan Sankhya (LIN), trade name or district.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="relative">
              <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden />
              <Input
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="e.g. LIN-1082-9923-4120 or Peenya"
                aria-label="Search establishments"
                className="pl-9"
              />
            </div>
            <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
              {matches.map((e) => (
                <button
                  key={e.lin}
                  onClick={() => setLin(e.lin)}
                  className={cn(
                    "rounded-lg border p-3 text-left transition-all hover:-translate-y-0.5 hover:shadow-sm",
                    e.lin === lin && "border-primary bg-primary/5",
                  )}
                >
                  <p className="text-sm font-semibold">{e.name}</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">{e.lin}</p>
                  <p className="mt-1 text-xs font-semibold" style={{ color: BAND_META[bandOf(e.score)].color }}>
                    {BAND_META[bandOf(e.score)].emoji} {e.score}/100
                  </p>
                </button>
              ))}
              {matches.length === 0 ? (
                <p className="text-sm text-muted-foreground">No establishment matches that search.</p>
              ) : null}
            </div>
          </CardContent>
        </Card>
      </Section>

      <Section>
        <div className="grid gap-5 lg:grid-cols-3">
          <Card className="lg:col-span-1">
            <CardHeader>
              <CardTitle className="text-base">{est.name}</CardTitle>
              <CardDescription>
                {est.lin} · {est.sector}
              </CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col items-center gap-4">
              <RiskGauge score={est.score} />
              <div className="w-full space-y-1 text-sm">
                <Row label="District" value={est.district} />
                <Row label="Cluster" value={est.cluster} />
                <Row label="Workers on roll" value={String(est.workers)} />
                <Row label="Registers digitised" value={`${est.registers} of 14`} />
                <Row label="Last inspection" value={est.lastInspection} />
              </div>
            </CardContent>
          </Card>

          <div className="grid gap-4 lg:col-span-2">
            <div className="grid gap-4 sm:grid-cols-3">
              <StatCard label="Open findings" value={String(open.length)} accent="red" />
              <StatCard label="Critical severity" value={String(open.filter((f) => f.severity === "critical").length)} accent="saffron" />
              <StatCard label="Verified compliant clauses" value={String(est.findings.length - open.length)} accent="green" />
            </div>
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">Six-month score trajectory</CardTitle>
                <CardDescription>Recomputed after every document ingestion and filing event.</CardDescription>
              </CardHeader>
              <CardContent className="h-56">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={est.trend} margin={{ left: -18, right: 8, top: 8 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                    <XAxis dataKey="month" tick={{ fontSize: 12, fill: "var(--muted-foreground)" }} />
                    <YAxis domain={[0, 100]} tick={{ fontSize: 12, fill: "var(--muted-foreground)" }} />
                    <ReTooltip
                      contentStyle={{
                        background: "var(--card)",
                        border: "1px solid var(--border)",
                        borderRadius: 8,
                        color: "var(--card-foreground)",
                        fontSize: 12,
                      }}
                    />
                    <Line type="monotone" dataKey="score" stroke={meta.color} strokeWidth={3} dot={{ r: 3 }} />
                  </LineChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>
        </div>
      </Section>

      <Section
        title="Clause-by-clause breakdown"
        subtitle="Every line is traceable to a section of the four Labour Codes, with penalty exposure and a plain-language remedy."
      >
        <label className="mb-4 flex w-fit cursor-pointer items-center gap-3 rounded-lg border bg-card px-3 py-2 text-sm">
          <Switch checked={iconMode} onCheckedChange={toggleIconMode} aria-label="Low-literacy icon mode" />
          <span>
            <strong>Low-literacy icon mode</strong> — turn legal tables into traffic-light cards with audio
          </span>
        </label>

        {iconMode ? (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {est.findings.map((f) => {
              const good = f.severity === "compliant";
              const color = good ? "var(--risk-low)" : f.severity === "minor" ? "var(--risk-mid)" : "var(--risk-high)";
              return (
                <div
                  key={f.id}
                  className="animate-rise rounded-2xl border-4 p-5 text-center"
                  style={{ borderColor: color, backgroundColor: `color-mix(in oklab, ${color} 10%, var(--card))` }}
                >
                  <p className="text-5xl" aria-hidden>
                    {SEV_ICON[f.severity]}
                  </p>
                  <p className="mt-3 text-lg font-bold" style={{ color }}>
                    {good ? (lang === "hi" ? "सब ठीक है" : "All good") : lang === "hi" ? "ध्यान दें" : "Needs fixing"}
                  </p>
                  <p className="mt-2 text-base font-medium leading-snug">
                    {lang === "hi" ? f.resolveHi : f.resolve}
                  </p>
                  <SpeakButton
                    className="mt-3"
                    size="default"
                    text={`${lang === "hi" ? f.observationHi : f.observation} ${lang === "hi" ? f.resolveHi : f.resolve}`}
                  />
                </div>
              );
            })}
          </div>
        ) : (
          <div className="grid gap-4">
            {est.findings.map((f) => (
              <Card key={f.id} className="animate-rise">
                <CardContent className="grid gap-3 pt-6 md:grid-cols-[1fr_auto]">
                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge variant={f.severity === "compliant" ? "secondary" : "destructive"} className="uppercase">
                        {f.severity}
                      </Badge>
                      <Badge variant="outline">{f.code} Code</Badge>
                      <span className="text-xs font-semibold text-primary">{f.section}</span>
                    </div>
                    <h3 className="mt-2 font-display text-base font-semibold">{f.title}</h3>
                    <p className="mt-1 text-sm">{lang === "hi" ? f.observationHi : f.observation}</p>
                    <p className="mt-2 text-sm text-muted-foreground">
                      <strong className="text-foreground">Penalty exposure:</strong> {f.penalty}
                    </p>
                    <p className="mt-2 rounded-lg bg-secondary p-2 text-sm">
                      <strong>How to resolve:</strong> {lang === "hi" ? f.resolveHi : f.resolve}
                    </p>
                  </div>
                  <div className="flex flex-col items-start gap-2 md:items-end">
                    <span className="text-xs text-muted-foreground">Score impact</span>
                    <span className="font-display text-2xl font-bold" style={{ color: f.weight ? "var(--risk-high)" : "var(--risk-low)" }}>
                      {f.weight ? `-${f.weight}` : "0"}
                    </span>
                    <SpeakButton text={`${f.title}. ${lang === "hi" ? f.observationHi : f.observation}`} />
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </Section>
    </>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-3 border-b py-1.5 last:border-0">
      <span className="text-muted-foreground">{label}</span>
      <span className="text-right font-medium">{value}</span>
    </div>
  );
}
